[package]
name = "fm8"
version = "0.1.1"
description = "A Tauri App"
authors = ["MintaoKaf"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
# The `_lib` suffix may seem redundant but it is necessary
# to make the lib name unique and wouldn't conflict with the bin name.
# This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
name = "fm8_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.2.0", features = [] }

[dependencies]
tauri = { version = "2.5.1", features = ["default", "devtools"] }
tauri-plugin-opener = "2.2.6"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1.45.0", features = ["full"] }
tokio-macros = "2.5.0"
chrono = "0.4.41"
winapi = "0.3.9"
futures = { version = "0.3.31", features = [] }

