


pub static TELEMETRY_FIELDS: &[TelemetryDataField] = &[
    TelemetryDataField { name: "IsRaceOn", type_name: "S32", offset: 0, bytes: 4, description: "= 1 when race is on. = 0 when in menus/race stopped." },
    TelemetryDataField { name: "TimestampMS", type_name: "U32", offset: 4, bytes: 4, description: "Can overflow to 0 eventually." },
    TelemetryDataField { name: "EngineMaxRpm", type_name: "F32", offset: 8, bytes: 4, description: "Maximum RPM of the engine." },
    TelemetryDataField { name: "EngineIdleRpm", type_name: "F32", offset: 12, bytes: 4, description: "Idle RPM of the engine." },
    TelemetryDataField { name: "CurrentEngineRpm", type_name: "F32", offset: 16, bytes: 4, description: "Current RPM of the engine." },
    TelemetryDataField { name: "AccelerationX", type_name: "F32", offset: 20, bytes: 4, description: "Acceleration in the car's local space (X = right)." },
    TelemetryDataField { name: "AccelerationY", type_name: "F32", offset: 24, bytes: 4, description: "Acceleration in the car's local space (Y = up)." },
    TelemetryDataField { name: "AccelerationZ", type_name: "F32", offset: 28, bytes: 4, description: "Acceleration in the car's local space (Z = forward)." },
    TelemetryDataField { name: "VelocityX", type_name: "F32", offset: 32, bytes: 4, description: "Velocity in the car's local space (X = right)." },
    TelemetryDataField { name: "VelocityY", type_name: "F32", offset: 36, bytes: 4, description: "Velocity in the car's local space (Y = up)." },
    TelemetryDataField { name: "VelocityZ", type_name: "F32", offset: 40, bytes: 4, description: "Velocity in the car's local space (Z = forward)." },
    TelemetryDataField { name: "AngularVelocityX", type_name: "F32", offset: 44, bytes: 4, description: "Angular velocity in the car's local space (X = pitch)." },
    TelemetryDataField { name: "AngularVelocityY", type_name: "F32", offset: 48, bytes: 4, description: "Angular velocity in the car's local space (Y = yaw)." },
    TelemetryDataField { name: "AngularVelocityZ", type_name: "F32", offset: 52, bytes: 4, description: "Angular velocity in the car's local space (Z = roll)." },
    TelemetryDataField { name: "Yaw", type_name: "F32", offset: 56, bytes: 4, description: "Yaw angle of the car." },
    TelemetryDataField { name: "Pitch", type_name: "F32", offset: 60, bytes: 4, description: "Pitch angle of the car." },
    TelemetryDataField { name: "Roll", type_name: "F32", offset: 64, bytes: 4, description: "Roll angle of the car." },
    TelemetryDataField { name: "NormalizedSuspensionTravelFrontLeft", type_name: "F32", offset: 68, bytes: 4, description: "Normalized suspension travel (0.0 = max stretch, 1.0 = max compression) for front left wheel." },
    TelemetryDataField { name: "NormalizedSuspensionTravelFrontRight", type_name: "F32", offset: 72, bytes: 4, description: "Normalized suspension travel (0.0 = max stretch, 1.0 = max compression) for front right wheel." },
    TelemetryDataField { name: "NormalizedSuspensionTravelRearLeft", type_name: "F32", offset: 76, bytes: 4, description: "Normalized suspension travel (0.0 = max stretch, 1.0 = max compression) for rear left wheel." },
    TelemetryDataField { name: "NormalizedSuspensionTravelRearRight", type_name: "F32", offset: 80, bytes: 4, description: "Normalized suspension travel (0.0 = max stretch, 1.0 = max compression) for rear right wheel." },
    TelemetryDataField { name: "TireSlipRatioFrontLeft", type_name: "F32", offset: 84, bytes: 4, description: "Normalized tire slip ratio (0 = 100% grip, |ratio| > 1.0 = loss of grip) for front left tire." },
    TelemetryDataField { name: "TireSlipRatioFrontRight", type_name: "F32", offset: 88, bytes: 4, description: "Normalized tire slip ratio (0 = 100% grip, |ratio| > 1.0 = loss of grip) for front right tire." },
    TelemetryDataField { name: "TireSlipRatioRearLeft", type_name: "F32", offset: 92, bytes: 4, description: "Normalized tire slip ratio (0 = 100% grip, |ratio| > 1.0 = loss of grip) for rear left tire." },
    TelemetryDataField { name: "TireSlipRatioRearRight", type_name: "F32", offset: 96, bytes: 4, description: "Normalized tire slip ratio (0 = 100% grip, |ratio| > 1.0 = loss of grip) for rear right tire." },
    TelemetryDataField { name: "WheelRotationSpeedFrontLeft", type_name: "F32", offset: 100, bytes: 4, description: "Wheel rotation speed in radians/sec for front left wheel." },
    TelemetryDataField { name: "WheelRotationSpeedFrontRight", type_name: "F32", offset: 104, bytes: 4, description: "Wheel rotation speed in radians/sec for front right wheel." },
    TelemetryDataField { name: "WheelRotationSpeedRearLeft", type_name: "F32", offset: 108, bytes: 4, description: "Wheel rotation speed in radians/sec for rear left wheel." },
    TelemetryDataField { name: "WheelRotationSpeedRearRight", type_name: "F32", offset: 112, bytes: 4, description: "Wheel rotation speed in radians/sec for rear right wheel." },
    TelemetryDataField { name: "WheelOnRumbleStripFrontLeft", type_name: "S32", offset: 116, bytes: 4, description: "= 1 when wheel is on rumble strip, = 0 when off (front left wheel)." },
    TelemetryDataField { name: "WheelOnRumbleStripFrontRight", type_name: "S32", offset: 120, bytes: 4, description: "= 1 when wheel is on rumble strip, = 0 when off (front right wheel)." },
    TelemetryDataField { name: "WheelOnRumbleStripRearLeft", type_name: "S32", offset: 124, bytes: 4, description: "= 1 when wheel is on rumble strip, = 0 when off (rear left wheel)." },
    TelemetryDataField { name: "WheelOnRumbleStripRearRight", type_name: "S32", offset: 128, bytes: 4, description: "= 1 when wheel is on rumble strip, = 0 when off (rear right wheel)." },
    TelemetryDataField { name: "WheelInPuddleDepthFrontLeft", type_name: "F32", offset: 132, bytes: 4, description: "= from 0 to 1, where 1 is the deepest puddle (front left wheel)." },
    TelemetryDataField { name: "WheelInPuddleDepthFrontRight", type_name: "F32", offset: 136, bytes: 4, description: "= from 0 to 1, where 1 is the deepest puddle (front right wheel)." },
    TelemetryDataField { name: "WheelInPuddleDepthRearLeft", type_name: "F32", offset: 140, bytes: 4, description: "= from 0 to 1, where 1 is the deepest puddle (rear left wheel)." },
    TelemetryDataField { name: "WheelInPuddleDepthRearRight", type_name: "F32", offset: 144, bytes: 4, description: "= from 0 to 1, where 1 is the deepest puddle (rear right wheel)." },
    TelemetryDataField { name: "SurfaceRumbleFrontLeft", type_name: "F32", offset: 148, bytes: 4, description: "Non-dimensional surface rumble values passed to controller force feedback (front left wheel)." },
    TelemetryDataField { name: "SurfaceRumbleFrontRight", type_name: "F32", offset: 152, bytes: 4, description: "Non-dimensional surface rumble values passed to controller force feedback (front right wheel)." },
    TelemetryDataField { name: "SurfaceRumbleRearLeft", type_name: "F32", offset: 156, bytes: 4, description: "Non-dimensional surface rumble values passed to controller force feedback (rear left wheel)." },
    TelemetryDataField { name: "SurfaceRumbleRearRight", type_name: "F32", offset: 160, bytes: 4, description: "Non-dimensional surface rumble values passed to controller force feedback (rear right wheel)." },
    TelemetryDataField { name: "TireSlipAngleFrontLeft", type_name: "F32", offset: 164, bytes: 4, description: "Normalized tire slip angle (0 = 100% grip, |angle| > 1.0 = loss of grip) for front left tire." },
    TelemetryDataField { name: "TireSlipAngleFrontRight", type_name: "F32", offset: 168, bytes: 4, description: "Normalized tire slip angle (0 = 100% grip, |angle| > 1.0 = loss of grip) for front right tire." },
    TelemetryDataField { name: "TireSlipAngleRearLeft", type_name: "F32", offset: 172, bytes: 4, description: "Normalized tire slip angle (0 = 100% grip, |angle| > 1.0 = loss of grip) for rear left tire." },
    TelemetryDataField { name: "TireSlipAngleRearRight", type_name: "F32", offset: 176, bytes: 4, description: "Normalized tire slip angle (0 = 100% grip, |angle| > 1.0 = loss of grip) for rear right tire." },
    TelemetryDataField { name: "TireCombinedSlipFrontLeft", type_name: "F32", offset: 180, bytes: 4, description: "Normalized tire combined slip (0 = 100% grip, |slip| > 1.0 = loss of grip) for front left tire." },
    TelemetryDataField { name: "TireCombinedSlipFrontRight", type_name: "F32", offset: 184, bytes: 4, description: "Normalized tire combined slip (0 = 100% grip, |slip| > 1.0 = loss of grip) for front right tire." },
    TelemetryDataField { name: "TireCombinedSlipRearLeft", type_name: "F32", offset: 188, bytes: 4, description: "Normalized tire combined slip (0 = 100% grip, |slip| > 1.0= loss of grip) for rear left tire." },
    TelemetryDataField { name: "TireCombinedSlipRearRight", type_name: "F32", offset: 192, bytes: 4, description: "Normalized tire combined slip (0 = 100% grip, |slip| > 1.0 = loss of grip) for rear right tire." },
    TelemetryDataField { name: "SuspensionTravelMetersFrontLeft", type_name: "F32", offset: 196, bytes: 4, description: "Actual suspension travel in meters for front left wheel." },
    TelemetryDataField { name: "SuspensionTravelMetersFrontRight", type_name: "F32", offset: 200, bytes: 4, description: "Actual suspension travel in meters for front right wheel." },
    TelemetryDataField { name: "SuspensionTravelMetersRearLeft", type_name: "F32", offset: 204, bytes: 4, description: "Actual suspension travel in meters for rear left wheel." },
    TelemetryDataField { name: "SuspensionTravelMetersRearRight", type_name: "F32", offset: 208, bytes: 4, description: "Actual suspension travel in meters for rear right wheel." },
    TelemetryDataField { name: "CarOrdinal", type_name: "S32", offset: 212, bytes: 4, description: "Unique ID of the car make/model." },
    TelemetryDataField { name: "CarClass", type_name: "S32", offset: 216, bytes: 4, description: "Between 0 (D -- worst cars) and 7 (X class -- best cars) inclusive." },
    TelemetryDataField { name: "CarPerformanceIndex", type_name: "S32", offset: 220, bytes: 4, description: "Between 100 (worst car) and 999 (best car) inclusive." },
    TelemetryDataField { name: "DrivetrainType", type_name: "S32", offset: 224, bytes: 4, description: "0 = FWD, 1 = RWD, 2 = AWD." },
    TelemetryDataField { name: "NumCylinders", type_name: "S32", offset: 228, bytes: 4, description: "Number of cylinders in the engine." },
    TelemetryDataField { name: "PositionX", type_name: "F32", offset: 232, bytes: 4, description: "X coordinate of the car's position." },
    TelemetryDataField { name: "PositionY", type_name: "F32", offset: 236, bytes: 4, description: "Y coordinate of the car's position." },
    TelemetryDataField { name: "PositionZ", type_name: "F32", offset: 240, bytes: 4, description: "Z coordinate of the car's position." },
    TelemetryDataField { name: "Speed", type_name: "F32", offset: 244, bytes: 4, description: "Current speed of the car." },
    TelemetryDataField { name: "Power", type_name: "F32", offset: 248, bytes: 4, description: "Current power output of the engine." },
    TelemetryDataField { name: "Torque", type_name: "F32", offset: 252, bytes: 4, description: "Current torque output of the engine." },
    TelemetryDataField { name: "TireTempFrontLeft", type_name: "F32", offset: 256, bytes: 4, description: "Temperature of the front left tire." },
    TelemetryDataField { name: "TireTempFrontRight", type_name: "F32", offset: 260, bytes: 4, description: "Temperature of the front right tire." },
    TelemetryDataField { name: "TireTempRearLeft", type_name: "F32", offset: 264, bytes: 4, description: "Temperature of the rear left tire." },
    TelemetryDataField { name: "TireTempRearRight", type_name: "F32", offset: 268, bytes: 4, description: "Temperature of the rear right tire." },
    TelemetryDataField { name: "Boost", type_name: "F32", offset: 272, bytes: 4, description: "Current boost level." },
    TelemetryDataField { name: "Fuel", type_name: "F32", offset: 276, bytes: 4, description: "Remaining fuel in the car." },
    TelemetryDataField { name: "DistanceTraveled", type_name: "F32", offset: 280, bytes: 4, description: "Total distance traveled by the car." },
    TelemetryDataField { name: "BestLap", type_name: "F32", offset: 284, bytes: 4, description: "Best lap time of the car." },
    TelemetryDataField { name: "LastLap", type_name: "F32", offset: 288, bytes: 4, description: "Time of the last completed lap." },
    TelemetryDataField { name: "CurrentLap", type_name: "F32", offset: 292, bytes: 4, description: "Time of the current lap." },
    TelemetryDataField { name: "CurrentRaceTime", type_name: "F32", offset: 296, bytes: 4, description: "Total race time elapsed." },
    TelemetryDataField { name: "LapNumber", type_name: "U16", offset: 300, bytes: 2, description: "Current lap number." },
    TelemetryDataField { name: "RacePosition", type_name: "U8", offset: 302, bytes: 1, description: "Current race position of the car." },
    TelemetryDataField { name: "Accel", type_name: "U8", offset: 303, bytes: 1, description: "Current acceleration input." },
    TelemetryDataField { name: "Brake", type_name: "U8", offset: 304, bytes: 1, description: "Current brake input." },
    TelemetryDataField { name: "Clutch", type_name: "U8", offset: 305, bytes: 1, description: "Current clutch input." },
    TelemetryDataField { name: "HandBrake", type_name: "U8", offset: 306, bytes: 1, description: "Current handbrake input." },
    TelemetryDataField { name: "Gear", type_name: "U8", offset: 307, bytes: 1, description: "Current gear selected." },
    TelemetryDataField { name: "Steer", type_name: "S8", offset: 308, bytes: 1, description: "Current steering input." },
    TelemetryDataField { name: "NormalizedDrivingLine", type_name: "S8", offset: 309, bytes: 1, description: "Normalized driving line input." },
    TelemetryDataField { name: "NormalizedAIBrakeDifference", type_name: "S8", offset: 310, bytes: 1, description: "Normalized AI brake difference." },
    TelemetryDataField { name: "TireWearFrontLeft", type_name: "F32", offset: 311, bytes: 4, description: "Wear level of the front left tire." },
    TelemetryDataField { name: "TireWearFrontRight", type_name: "F32", offset: 315, bytes: 4, description: "Wear level of the front right tire." },
    TelemetryDataField { name: "TireWearRearLeft", type_name: "F32", offset: 319, bytes: 4, description: "Wear level of the rear left tire." },
    TelemetryDataField { name: "TireWearRearRight", type_name: "F32", offset: 323, bytes: 4, description: "Wear level of the rear right tire." },
    TelemetryDataField { name: "TrackOrdinal", type_name: "S32", offset: 327, bytes: 4, description: "Unique ID for the track." },
];

#[allow(dead_code)]
#[derive(Debug, Copy, Clone)]
pub struct TelemetryDataField {
    pub name: &'static str,
    pub type_name: &'static str,
    pub offset: usize,
    pub bytes: usize,
    pub description: &'static str,
}
