name: Windows Release Build

on:
  push:
    tags:
      - 'v*'  # 触发条件：当推送以 v 开头的 tag 时（例如 v1.0.0）
jobs:
  build-and-release:
    runs-on: windows-latest
    permissions:
      contents: write  # 需要写入权限来创建 release

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup pnpm
      # You may pin to the exact commit or the version.
      # uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda
      uses: pnpm/action-setup@v4.1.0
      with:
        # Version of pnpm to install
        version: 10.11.0
        # Where to store pnpm files
        # If specified, run `pnpm install`
        run_install: true # optional, default is null

    - name: Setup Rust
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        target: x86_64-pc-windows-msvc  # Windows 目标平台
        profile: minimal
        toolchain: stable

    - name: Build Release
      run: pnpm tauri build

    # - name: Rename executable (optional)
    #   shell: powershell
    #   run: |
    #     $exePath = "target/release/hello_cargo.exe"
    #     $newName = "my_rust_pratice-${{ github.ref_name }}.exe"
    #     Rename-Item -Path $exePath -NewName $newName
      # 替换 your_project_name 为你的 crate 名称

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        name: ${{ github.ref_name }}
        tag_name: ${{ github.ref_name }}
        body: "Windows build for ${{ github.ref_name }}"
        # files: |
        #   target/release/my_rust_pratice-*.exe
        files: |
            target/release/fm8.exe
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
